[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
build_flags = -I${PROJECT_DIR}/include
lib_ignore = LittleFS_esp32
lib_deps = 
        adafruit/DHT sensor library 
        bblanchon/ArduinoJson @ ^7.0.0
        adafruit/Adafruit Unified Sensor


